import React, { createContext, useContext, useState, useEffect } from 'react';
import { LanguageCode } from '../data/mockData';

export type TranslationKey = string;

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
}

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Branding & Common
    'brand.name': 'NALAM AI',
    'brand.subtitle': 'AI-Assisted Symptom Triage',
    'brand.initiative': 'Primary Healthcare Triage Initiative',
    'common.emergency': 'Emergency: 108 / 104',
    'common.emergencyDial': 'Emergency? Dial 108',
    'common.staffLogin': 'Staff Login',
    'common.signOut': 'Sign Out',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.acknowledge': 'Acknowledge',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred. Please try again.',
    'common.disclaimer': 'Not a medical diagnosis. In medical emergencies, immediately call 108.',
    'common.privacyNotice': 'Clinical Privacy Notice',
    'common.fieldWorkerGuidelines': 'Field Worker Guidelines',
    'common.copyright': '© Rural Health Mission • National Health Portal',
    'common.activeSession': 'Active Session',
    'common.confidentialAssessment': 'Confidential Clinical Assessment',
    'common.companion': 'NALAM Companion',
    'common.today': 'Today',
    'common.priority': 'Priority',

    // Sidebar Items
    'nav.home': 'Home',
    'nav.symptomChat': 'Symptom Chat',
    'nav.triageRecord': 'Triage Record',
    'nav.staffLogin': 'Staff Login',
    'nav.staffDashboard': 'PHC Triage Queue',
    'nav.caseReview': 'Case Review',
    'nav.phcLocator': 'Nearby PHC Center',

    // Header Links
    'header.symptomCheck': 'Symptom Check',
    'header.howItWorks': 'How It Works',
    'header.nearbyPhc': 'Nearby PHC Center',

    // Home Hero
    'home.heroPill': 'NALAM AI',
    'home.heroTitle1': 'Your AI Health',
    'home.heroTitle2': 'Assistant',
    'home.heroSubtitle': 'Describe your symptoms. Get guidance on what to do next.',
    'home.assessmentTitle': 'Immediate Clinical Assessment',
    'home.assessmentSubtitle': 'No account needed • Private & Secure',
    'home.startCheck': 'Start Health Check',
    'home.speakInLanguage': 'Speak in Your Language',
    'home.listening': 'Listening to your voice...',
    'home.listeningDesc': 'Speak now in English, Tamil, or Hindi',
    'home.continueChat': 'Continue to Symptom Chat with this text',
    'home.speechUnsupported': 'Voice recognition is not supported in this browser. Please type your symptoms in Symptom Chat.',
    'home.speechDenied': 'Microphone access was denied. Please allow microphone permission in your browser.',
    'home.speechError': 'Could not recognize speech. Please speak clearly or type.',
    'home.reviewSpoken': 'Review & Edit Your Spoken Symptoms:',
    'home.clearText': 'Clear',

    // Home 4-Feature Strip
    'feat.quickAssessment': 'Quick Assessment',
    'feat.quickAssessmentSub': 'Get guidance in minutes',
    'feat.ruralCommunity': 'For Rural Communities',
    'feat.ruralCommunitySub': 'Designed for local needs',
    'feat.safePrivate': 'Safe & Private',
    'feat.safePrivateSub': 'Your data is protected',
    'feat.accessibleCare': 'Accessible Care',
    'feat.accessibleCareSub': 'Connect to nearby PHCs',

    // Symptom Chat Screen
    'chat.welcome': 'Hello! I am NALAM, your rural health assistant. What symptoms are you or your family member experiencing right now?',
    'chat.defaultPatientMsg': 'My mother has had a persistent dry cough and mild fever for 3 days. She also feels fatigued.',
    'chat.botFollowUp': 'I understand. Does she have any chest tightness, shortness of breath, or difficulty breathing when resting?',
    'chat.quickOption1': 'No breathing difficulty',
    'chat.quickOption2': 'Mild chest heaviness',
    'chat.quickOption3': 'Fever higher today',
    'chat.inputPlaceholder': 'Type your symptoms or tap the microphone to speak...',
    'chat.send': 'Send',
    'chat.listeningState': 'Listening... Speak now',
    'chat.reviewTriageBtn': 'View Official Triage Record & Guidance',
    'chat.tapToSpeak': 'Tap to speak',
    'chat.stopSpeaking': 'Stop listening',
    'chat.speechHelp': 'You can speak or type in English, Tamil, or Hindi. Everything shared is strictly confidential and secure.',
    'chat.consultPhcNotice': 'Since symptoms are persistent, we recommend visiting the nearest Primary Health Center (PHC) for a basic blood count and vitals checkup.',
    'chat.emergencyWarning': 'Please note: Breathing difficulty or chest heaviness warrants immediate clinical evaluation. We have generated Official Triage Record #TN-4082-89.',

    // Triage Record Screen
    'triage.recordTitle': 'Official Triage Record',
    'triage.evaluatedToday': 'Evaluated Today • 10:42 AM IST',
    'triage.badgeRecommended': 'Medical Attention Recommended',
    'triage.headline': 'Visit Your Primary Health Center',
    'triage.body': 'Your symptoms should be evaluated by a healthcare professional at your local Primary Health Center within 24 hours.',
    'triage.code': 'Triage Code',
    'triage.priorityLevel': 'Priority 2',
    'triage.codeSub': 'Sub-acute • Timely PHC Care',
    'triage.observation': 'Observation',
    'triage.observationDesc': 'Persistent febrile state with dry cough • Nil acute cyanosis',
    'triage.suggestedAction': 'Suggested Action',
    'triage.suggestedActionDesc': 'CBC + Sputum / Viral screening at nearest PHC',
    'triage.clinicalGuidanceTitle': 'Clinical Guidance & Next Steps',
    'triage.step1': 'Avoid strenuous physical activity and rest in a well-ventilated room.',
    'triage.step2': 'Maintain oral hydration with boiled water, ORS, or tender coconut water.',
    'triage.step3': 'If high fever (>102°F), rapid breathing, or chest tightness develops, dial 108 immediately.',
    'triage.findNearbyPhc': 'Locate Nearest PHC & Check Doctors',
    'triage.shareRecord': 'Share / Print Record',
    'triage.toastShared': 'Triage record link copied to clipboard!',
    'triage.emergencyHelpline': 'Emergency Ambulance: 108 • 24/7 Health Helpline: 104',

    // PHC Locator Screen
    'locator.badge': 'National Rural Health Mission • PHC Directory',
    'locator.title': 'Nearby Primary Health Centers (PHC)',
    'locator.subtitle': 'Verified government health stations synced with your NALAM AI Triage Record #TN-4082-89.',
    'locator.backToTriage': '← Back to Triage Record',
    'locator.newCheck': 'New Symptom Check',
    'locator.opdOpen': '24/7 Emergency & OPD Open',
    'locator.queueEstimate': 'Priority triage queue',
    'locator.availableBeds': 'Observation Beds Available',
    'locator.callPhc': 'Call Center',
    'locator.bookSlot': 'Book Token / Notify PHC',
    'locator.bookedSuccess': 'Notification sent to PHC duty nurse. Please arrive at the facility.',
    'locator.distance': 'km away',

    // Staff Login Screen
    'login.badge': 'PHC Clinical Node 4082 • Online',
    'login.mission': 'Rural Health Mission',
    'login.authorizedTerminal': 'Authorized Staff Terminal',
    'login.title': 'NALAM AI Staff Station',
    'login.subtitle': 'Assisting medical officers, staff nurses, and field workers with rapid clinical prioritization.',
    'login.staffIdLabel': 'Staff ID / Health Worker ID',
    'login.passwordLabel': 'Password / Access PIN',
    'login.rememberTerminal': 'Remember terminal for this shift',
    'login.signInBtn': 'Sign In to Triage Station',
    'login.signingIn': 'Authenticating Credentials...',
    'login.demoHint': 'Demo Station Access: Credentials pre-filled for Testing',

    // Staff Dashboard Screen
    'dashboard.portal': 'PHC Staff Portal',
    'dashboard.stationNode': 'Alangulam Primary Health Center (Node 4082)',
    'dashboard.district': 'Tirunelveli District Cluster',
    'dashboard.liveStream': 'Live Triage Stream Active',
    'dashboard.dutyDoctor': 'Duty MO: Dr. Priya R.',
    'dashboard.tabQueue': 'Triage Queue',
    'dashboard.tabActive': 'Active Cases',
    'dashboard.tabReferrals': 'Urgent Referrals & 108',
    'dashboard.tabAnalytics': 'Epidemic Pulse',
    'dashboard.filterAll': 'All Intake',
    'dashboard.filterEmergency': 'Emergency (Red)',
    'dashboard.filterUrgent': 'Urgent (Orange)',
    'dashboard.filterRoutine': 'Routine (Green)',
    'dashboard.totalCases': 'Total Cases',
    'dashboard.todayIntake': "Today's Intake",
    'dashboard.emergency': 'Emergency',
    'dashboard.urgent': 'Urgent',
    'dashboard.routine': 'Routine',
    'dashboard.priority1': 'Priority 1',
    'dashboard.priority2': 'Priority 2',
    'dashboard.standard': 'Standard',
    'dashboard.immediateDoctorReview': 'Immediate doctor review',
    'dashboard.within2Hours': 'Within 2 hours',
    'dashboard.standardQueue': 'Standard queue',
    'dashboard.priorityCases': 'Priority Cases',
    'dashboard.updatedLive': 'Updated Live',
    'dashboard.allCasesFilter': 'All Cases',
    'dashboard.tableCaseId': 'Case ID',
    'dashboard.tableDemographic': 'Demographic',
    'dashboard.tableChief': 'Chief Symptoms & Complaint',
    'dashboard.tableChiefSymptom': 'Chief Symptom',
    'dashboard.tableSeverity': 'Urgency Level',
    'dashboard.tableTriageLevel': 'Triage Level',
    'dashboard.tableIntakeTime': 'Intake Time',
    'dashboard.tableTime': 'Time',
    'dashboard.tableAction': 'Action',
    'dashboard.medicalAttention': 'Medical Attention',
    'dashboard.reviewCase': 'Review Case',
    'dashboard.viewCase': 'View Case',
    'dashboard.reviewed': 'Reviewed',
    'dashboard.dispatchAmbulance': '108 ALS Dispatched',
    'dashboard.footerVerification': 'AI Auto-Triage confidence verified with ICMR primary health protocols',
    'dashboard.showingCases': 'Showing active cases',

    // Case Review Screen
    'case.back': '← Back to Triage Queue',
    'case.backToPriority': 'Back to Priority Cases',
    'case.caseReviewTitle': 'Comprehensive Clinical Case Review',
    'case.vitals': 'Field Baseline Vitals',
    'case.symptomsDetails': 'Reported Symptoms & Progression',
    'case.ashaReport': 'ASHA Worker Field Transcript',
    'case.voiceIntake': 'Audio Recording Intake',
    'case.playAudio': 'Play Patient Voice Note',
    'case.pauseAudio': 'Pause Voice Note',
    'case.actionChecklist': 'Clinical Directive Checklist',
    'case.markComplete': 'Approve & Route to Duty MO',
    'case.trigger108': 'Trigger 108 ALS Ambulance',
    'case.dispatch108': 'Dispatch 108 Ambulance',
    'case.ambulanceDispatched': '108 ALS Dispatched',
    'case.addNote': 'Add Doctor Note',
    'case.addClinicalNote': 'Add Clinical Note',
    'case.saveNote': 'Save Note',
    'case.cancel': 'Cancel',
    'case.notePlaceholder': 'Enter clinical observations, vitals recheck, or doctor directives...',
    'case.confirmAmbulanceTitle': 'Confirm 108 ALS Ambulance Dispatch',
    'case.confirmAmbulanceDesc': 'This will transmit a priority emergency request to the nearest 108 ALS unit with patient GPS coordinates and vital parameters.',
    'case.confirmDispatchBtn': 'Confirm Emergency Dispatch',
    'case.reviewedRouted': 'Approved & Routed to Doctor',
    'case.noteSaved': 'Clinical note saved and attached to record.',
  },

  ta: {
    // Branding & Common
    'brand.name': 'நலன் AI',
    'brand.subtitle': 'AI-உதவி அறிகுறி முன்னுரிமைப் பகுப்பாய்வு',
    'brand.initiative': 'கிராமப்புற ஆரம்ப சுகாதார முன்னுரிமை திட்டம்',
    'common.emergency': 'அவசர உதவி: 108 / 104',
    'common.emergencyDial': 'அவசர உதவிகளுக்கு 108-ஐ அழைக்கவும்',
    'common.staffLogin': 'பணியாளர் உள்நுழைவு',
    'common.signOut': 'வெளியேறு',
    'common.back': 'பின்செல்',
    'common.close': 'மூடு',
    'common.acknowledge': 'ஏற்றுக்கொண்டேன்',
    'common.loading': 'ஏற்றப்படுகிறது...',
    'common.error': 'பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
    'common.disclaimer': 'இது மருத்துவ நோய் கண்டறிதல் அல்ல. அவசர நிலைகளில் உடனே 108-ஐ அழைக்கவும்.',
    'common.privacyNotice': 'மருத்துவ தரவு பாதுகாப்பு அறிவிப்பு',
    'common.fieldWorkerGuidelines': 'கிராமப்புற களப்பணியாளர் வழிகாட்டுதல்கள்',
    'common.copyright': '© கிராமப்புற சுகாதார இயக்கம் • தேசிய சுகாதார இணையதளம்',
    'common.activeSession': 'செயலில் உள்ள அமர்வு',
    'common.confidentialAssessment': 'ரகசிய மருத்துவ மதிப்பீடு',
    'common.companion': 'நலன் துணைவர்',
    'common.today': 'இன்று',
    'common.priority': 'முன்னுரிமை',

    // Sidebar Items
    'nav.home': 'முகப்பு',
    'nav.symptomChat': 'அறிகுறி உரையாடல்',
    'nav.triageRecord': 'முன்னுரிமை அறிக்கை',
    'nav.staffLogin': 'பணியாளர் உள்நுழைவு',
    'nav.staffDashboard': 'ஆரம்ப சுகாதார நிலைய வரிசை',
    'nav.caseReview': 'நோயாளி பரிசீலனை',
    'nav.phcLocator': 'அருகிலுள்ள PHC மையம்',

    // Header Links
    'header.symptomCheck': 'அறிகுறி பரிசோதனை',
    'header.howItWorks': 'செயல்படும் விதம்',
    'header.nearbyPhc': 'அருகிலுள்ள PHC மையம்',

    // Home Hero
    'home.heroPill': 'நலன் AI',
    'home.heroTitle1': 'உங்கள் AI சுகாதார',
    'home.heroTitle2': 'உதவியாளர்',
    'home.heroSubtitle': 'உங்கள் உடல் அறிகுறிகளை விவரிக்கவும். அடுத்த கட்ட வழிகாட்டுதலை உடனே பெறவும்.',
    'home.assessmentTitle': 'உடனடி மருத்துவ மதிப்பீடு',
    'home.assessmentSubtitle': 'கணக்கு தேவையில்லை • தனிப்பட்ட & பாதுகாப்பானது',
    'home.startCheck': 'சுகாதார பரிசோதனையைத் தொடங்குங்கள்',
    'home.speakInLanguage': 'உங்கள் மொழியில் பேசுங்கள்',
    'home.listening': 'உங்கள் குரலைக் கேட்கிறது...',
    'home.listeningDesc': 'இப்போது தமிழில், ஆங்கிலத்தில் அல்லது இந்தியில் பேசலாம்',
    'home.continueChat': 'இந்த வாசகத்துடன் உரையாடலைத் தொடரவும்',
    'home.speechUnsupported': 'இந்த உலாவியில் குரல் உள்ளீடு வசதி ஆதரிக்கப்படவில்லை. தயவுசெய்து தட்டச்சு செய்யவும்.',
    'home.speechDenied': 'மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. தயவுசெய்து உலாவி அமைப்பில் மைக்ரோஃபோன் அனுமதியை வழங்கவும்.',
    'home.speechError': 'குரலை அடையாளம் காண முடியவில்லை. தெளிவாகப் பேசவும் அல்லது தட்டச்சு செய்யவும்.',
    'home.reviewSpoken': 'பேசிய அறிகுறிகளைச் சரிபார்த்து திருத்தவும்:',
    'home.clearText': 'அழி',

    // Home 4-Feature Strip
    'feat.quickAssessment': 'விரைவான மதிப்பீடு',
    'feat.quickAssessmentSub': 'நிமிடங்களில் மருத்துவ வழிகாட்டுதல்',
    'feat.ruralCommunity': 'கிராமப்புற மக்களுக்காக',
    'feat.ruralCommunitySub': 'உள்ளூர் தேவைகளுக்கு ஏற்ப வடிவமைக்கப்பட்டது',
    'feat.safePrivate': 'பாதுகாப்பானது & ரகசியமானது',
    'feat.safePrivateSub': 'உங்கள் தகவல்கள் பாதுகாக்கப்படுகின்றன',
    'feat.accessibleCare': 'எளிய மருத்துவ சேவை',
    'feat.accessibleCareSub': 'அருகிலுள்ள ஆரம்ப சுகாதார நிலையங்களை அணுகவும்',

    // Symptom Chat Screen
    'chat.welcome': 'வணக்கம்! நான் நலன், உங்கள் கிராமப்புற சுகாதார உதவியாளர். உங்களுக்கோ அல்லது குடும்பத்தினருக்கோ இப்போது என்ன அறிகுறிகள் உள்ளன?',
    'chat.defaultPatientMsg': 'என் தாய்க்கு 3 நாட்களாக வறட்டு இருமலும் மிதமான காய்ச்சலும் உள்ளது. மிகவும் சோர்வாகவும் உணர்கிறார்.',
    'chat.botFollowUp': 'புரிந்து கொண்டேன். அவருக்கு நெஞ்சு இறுக்கம், மூச்சுத் திணறல் அல்லது ஓய்வெடுக்கும் போது மூச்சு வாங்குதல் ஏதும் உள்ளதா?',
    'chat.quickOption1': 'மூச்சுத் திணறல் இல்லை',
    'chat.quickOption2': 'லேசான நெஞ்சு பாரம் உள்ளது',
    'chat.quickOption3': 'இன்று காய்ச்சல் அதிகம்',
    'chat.inputPlaceholder': 'உங்கள் அறிகுறிகளை தட்டச்சு செய்யவும் அல்லது பேச மைக்கை அழுத்தவும்...',
    'chat.send': 'அனுப்பு',
    'chat.listeningState': 'கேட்கிறது... இப்போது பேசவும்',
    'chat.reviewTriageBtn': 'அதிகாரப்பூர்வ முன்னுரிமை அறிக்கையைக் காண்க',
    'chat.tapToSpeak': 'பேச தட்டவும்',
    'chat.stopSpeaking': 'கேட்பதை நிறுத்து',
    'chat.speechHelp': 'நீங்கள் தமிழ், ஆங்கிலம் அல்லது இந்தியில் பேசலாம் அல்லது தட்டச்சு செய்யலாம். அனைத்தும் முற்றிலும் ரகசியமாக வைக்கப்படும்.',
    'chat.consultPhcNotice': 'அறிகுறிகள் நீடிப்பதால், இரத்தப் பரிசோதனை மற்றும் பொதுப் பரிசோதனைக்காக அருகிலுள்ள ஆரம்ப சுகாதார நிலையத்தை அணுகவும்.',
    'chat.emergencyWarning': 'கவனிக்கவும்: மூச்சுத் திணறல் அல்லது நெஞ்சு பாரம் இருந்தால் உடனடி மருத்துவ கவனிப்பு தேவை. முன்னுரிமை அறிக்கை #TN-4082-89 உருவாக்கப்பட்டுள்ளது.',

    // Triage Record Screen
    'triage.recordTitle': 'அதிகாரப்பூர்வ முன்னுரிமை அறிக்கை',
    'triage.evaluatedToday': 'மதிப்பீடு செய்யப்பட்டது • இன்று 10:42 AM IST',
    'triage.badgeRecommended': 'மருத்துவ கவனிப்பு பரிந்துரைக்கப்படுகிறது',
    'triage.headline': 'ஆரம்ப சுகாதார நிலையத்திற்குச் செல்லவும்',
    'triage.body': 'உங்கள் அறிகுறிகளை 24 மணி நேரத்திற்குள் உள்ளூர் ஆரம்ப சுகாதார நிலைய மருத்துவரிடம் காட்டி ஆலோசனை பெற வேண்டும்.',
    'triage.code': 'முன்னுரிமை குறியீடு',
    'triage.priorityLevel': 'முன்னுரிமை 2',
    'triage.codeSub': 'மிதமான தீவிரம் • சரியான நேரத்தில் PHC சிகிச்சை',
    'triage.observation': 'கண்காணிப்பு',
    'triage.observationDesc': 'வறட்டு இருமலுடன் கூடிய தொடர் காய்ச்சல் • கடுமையான மூச்சுத்திணறல் இல்லை',
    'triage.suggestedAction': 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
    'triage.suggestedActionDesc': 'அருகிலுள்ள ஆரம்ப சுகாதார நிலையத்தில் CBC மற்றும் சளி பரிசோதனை',
    'triage.clinicalGuidanceTitle': 'மருத்துவ வழிகாட்டுதல் & அடுத்த படிகள்',
    'triage.step1': 'கடினமான உடற்பயிற்சிகளைத் தவிர்த்து, காற்றோட்டமான அறையில் ஓய்வெடுக்கவும்.',
    'triage.step2': 'காய்ச்சிய நீர், ஓஆர்எஸ் அல்லது இளநீர் குடித்து உடலில் நீர்ச்சத்தை பராமரிக்கவும்.',
    'triage.step3': 'அதிக காய்ச்சல் (>102°F) அல்லது நெஞ்சு பாரம் ஏற்பட்டால், உடனே 108-ஐ அழைக்கவும்.',
    'triage.findNearbyPhc': 'அருகிலுள்ள PHC மையத்தைக் கண்டறிந்து மருத்துவர்களைப் பார்க்கவும்',
    'triage.shareRecord': 'அறிக்கையைப் பகிர் / அச்சிடு',
    'triage.toastShared': 'முன்னுரிமை அறிக்கை இணைப்பு நகலெடுக்கப்பட்டது!',
    'triage.emergencyHelpline': 'அவசர ஆம்புலன்ஸ்: 108 • 24/7 மருத்துவ உதவி: 104',

    // PHC Locator Screen
    'locator.badge': 'தேசிய கிராமப்புற சுகாதார இயக்கம் • PHC வழிகாட்டி',
    'locator.title': 'அருகிலுள்ள ஆரம்ப சுகாதார நிலையங்கள் (PHC)',
    'locator.subtitle': 'உங்கள் நலன் AI முன்னுரிமை அறிக்கை #TN-4082-89 உடன் இணைக்கப்பட்ட அரசு சுகாதார மையங்கள்.',
    'locator.backToTriage': '← முன்னுரிமை அறிக்கைக்குத் திரும்பு',
    'locator.newCheck': 'புதிய அறிகுறி பரிசோதனை',
    'locator.opdOpen': '24/7 அவசர சிகிச்சை மற்றும் வெளிநோயாளி பிரிவு திறந்துள்ளது',
    'locator.queueEstimate': 'முன்னுரிமை வரிசை காத்திருப்பு',
    'locator.availableBeds': 'கண்காணிப்பு படுக்கைகள் உள்ளன',
    'locator.callPhc': 'நிலையத்தை அழைக்கவும்',
    'locator.bookSlot': 'டோக்கன் பதிவு / நிலையத்திற்கு தெரிவிக்கவும்',
    'locator.bookedSuccess': 'ஆரம்ப சுகாதார நிலைய செவிலியருக்கு தகவல் தெரிவிக்கப்பட்டது. நிலையத்திற்கு வரவும்.',
    'locator.distance': 'கி.மீ தொலைவில்',

    // Staff Login Screen
    'login.badge': 'PHC மருத்துவ முனையம் 4082 • ஆன்லைன்',
    'login.mission': 'கிராமப்புற சுகாதார இயக்கம்',
    'login.authorizedTerminal': 'அங்கீகரிக்கப்பட்ட பணியாளர் தளம்',
    'login.title': 'நலன் AI பணியாளர் மையம்',
    'login.subtitle': 'மருத்துவர்கள், செவிலியர்கள் மற்றும் ஆஷா களப்பணியாளர்களுக்கு வேகமான மருத்துவ முன்னுரிமை உதவி.',
    'login.staffIdLabel': 'பணியாளர் ஐடி / சுகாதார ஊழியர் ஐடி',
    'login.passwordLabel': 'கடவுச்சொல் / பின் எண்',
    'login.rememberTerminal': 'இந்த முறைக்கான தளத்தை நினைவில் கொள்',
    'login.signInBtn': 'நிலையத்தில் உள்நுழையவும்',
    'login.signingIn': 'சான்றுகள் சரிபார்க்கப்படுகின்றன...',
    'login.demoHint': 'டெமோ அணுகல்: சோதனைக்கான விவரங்கள் முன்பே நிரப்பப்பட்டுள்ளன',

    // Staff Dashboard Screen
    'dashboard.portal': 'PHC பணியாளர் தளம்',
    'dashboard.stationNode': 'ஆலங்குளம் ஆரம்ப சுகாதார நிலையம் (முனையம் 4082)',
    'dashboard.district': 'திருநெல்வேலி மாவட்ட மண்டலம்',
    'dashboard.liveStream': 'நேரடி முன்னுரிமை தொடர் செயலில் உள்ளது',
    'dashboard.dutyDoctor': 'பணி மருத்துவர்: டாக்டர் பிரியா ஆர்.',
    'dashboard.tabQueue': 'முன்னுரிமை வரிசை',
    'dashboard.tabActive': 'செயலில் உள்ள வழக்குகள்',
    'dashboard.tabReferrals': 'அவசர பரிந்துரைகள் & 108',
    'dashboard.tabAnalytics': 'தொற்றுநோய் துடிப்பு',
    'dashboard.filterAll': 'அனைத்து வழக்குகள்',
    'dashboard.filterEmergency': 'அவசரம் (சிவப்பு)',
    'dashboard.filterUrgent': 'தீவிரம் (ஆரஞ்சு)',
    'dashboard.filterRoutine': 'வழக்கமானது (பச்சை)',
    'dashboard.totalCases': 'மொத்த வழக்குகள்',
    'dashboard.todayIntake': 'இன்றைய பதிவுகள்',
    'dashboard.emergency': 'அவசரம்',
    'dashboard.urgent': 'தீவிரம்',
    'dashboard.routine': 'வழக்கமானது',
    'dashboard.priority1': 'முன்னுரிமை 1',
    'dashboard.priority2': 'முன்னுரிமை 2',
    'dashboard.standard': 'நிலையானது',
    'dashboard.immediateDoctorReview': 'உடனடி மருத்துவர் பரிசீலனை',
    'dashboard.within2Hours': '2 மணி நேரத்திற்குள்',
    'dashboard.standardQueue': 'வழக்கமான வரிசை',
    'dashboard.priorityCases': 'முன்னுரிமை வழக்குகள்',
    'dashboard.updatedLive': 'நேரலையில் புதுப்பிக்கப்பட்டது',
    'dashboard.allCasesFilter': 'அனைத்து வழக்குகள்',
    'dashboard.tableCaseId': 'வழக்கு ஐடி',
    'dashboard.tableDemographic': 'நோயாளி விவரம்',
    'dashboard.tableChief': 'முக்கிய அறிகுறிகள் & புகார்',
    'dashboard.tableChiefSymptom': 'முக்கிய அறிகுறி',
    'dashboard.tableSeverity': 'முன்னுரிமை நிலை',
    'dashboard.tableTriageLevel': 'முன்னுரிமை நிலை',
    'dashboard.tableIntakeTime': 'பதிவு நேரம்',
    'dashboard.tableTime': 'நேரம்',
    'dashboard.tableAction': 'நடவடிக்கை',
    'dashboard.medicalAttention': 'மருத்துவ கவனிப்பு',
    'dashboard.reviewCase': 'பரிசீலிக்கவும்',
    'dashboard.viewCase': 'வழக்கைப் பார்',
    'dashboard.reviewed': 'பரிசீலிக்கப்பட்டது',
    'dashboard.dispatchAmbulance': '108 ஆம்புலன்ஸ் அனுப்பப்பட்டது',
    'dashboard.footerVerification': 'ICMR ஆரம்ப சுகாதார நெறிமுறைகளின்படி AI தானியங்கி முன்னுரிமை சரிபார்க்கப்பட்டது',
    'dashboard.showingCases': 'செயலில் உள்ள வழக்குகள் காட்டப்படுகின்றன',

    // Case Review Screen
    'case.back': '← முன்னுரிமை வரிசைக்குத் திரும்பு',
    'case.backToPriority': 'முன்னுரிமை வழக்குகளுக்குத் திரும்பு',
    'case.caseReviewTitle': 'முழுமையான நோயாளி மருத்துவ பரிசீலனை',
    'case.vitals': 'களப்பணியாளர் எடுத்த உடல் அளவீடுகள்',
    'case.symptomsDetails': 'பதிவு செய்யப்பட்ட அறிகுறிகள்',
    'case.ashaReport': 'ஆஷா பணியாளர் கள அறிக்கை',
    'case.voiceIntake': 'நோயாளி குரல் பதிவு விவரம்',
    'case.playAudio': 'குரல் பதிவைக் கேட்கவும்',
    'case.pauseAudio': 'குரல் பதிவை நிறுத்தவும்',
    'case.actionChecklist': 'மருத்துவ கட்டளை சரிபார்ப்புப் பட்டியல்',
    'case.markComplete': 'ஒப்புதல் அளித்து மருத்துவருக்கு அனுப்பவும்',
    'case.trigger108': '108 ஆம்புலன்ஸை உடனடியாக அழைக்கவும்',
    'case.dispatch108': '108 ஆம்புலன்ஸை அனுப்பு',
    'case.ambulanceDispatched': '108 ஆம்புலன்ஸ் அனுப்பப்பட்டது',
    'case.addNote': 'மருத்துவர் குறிப்பு சேர்க்கவும்',
    'case.addClinicalNote': 'மருத்துவ குறிப்பு சேர்க்க',
    'case.saveNote': 'குறிப்பைச் சேமி',
    'case.cancel': 'ரத்து செய்',
    'case.notePlaceholder': 'மருத்துவ அவதானிப்புகள் அல்லது மருத்துவர் வழிகாட்டுதல்களை உள்ளிடவும்...',
    'case.confirmAmbulanceTitle': '108 ஆம்புலன்ஸ் அழைப்பை உறுதிப்படுத்தவும்',
    'case.confirmAmbulanceDesc': 'இது நோயாளியின் இருப்பிடம் மற்றும் முக்கிய மருத்துவ அளவீடுகளுடன் அருகிலுள்ள 108 பிரிவுக்கு அவசர எச்சரிக்கையை அனுப்பும்.',
    'case.confirmDispatchBtn': 'அவசர ஆம்புலன்ஸை உறுதிப்படுத்து',
    'case.reviewedRouted': 'ஒப்புதல் அளிக்கப்பட்டு மருத்துவருக்கு அனுப்பப்பட்டது',
    'case.noteSaved': 'மருத்துவ குறிப்பு சேமிக்கப்பட்டு கோப்பில் இணைக்கப்பட்டது.',
  },

  hi: {
    // Branding & Common
    'brand.name': 'नलम AI',
    'brand.subtitle': 'एआई-सहायक लक्षण ट्राइएज',
    'brand.initiative': 'प्राथमिक स्वास्थ्य देखभाल ट्राइएज पहल',
    'common.emergency': 'आपातकालीन: 108 / 104',
    'common.emergencyDial': 'आपातकाल? डायल 108',
    'common.staffLogin': 'स्टाफ लॉगिन',
    'common.signOut': 'साइन आउट',
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.acknowledge': 'स्वीकार करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
    'common.disclaimer': 'यह एक चिकित्सीय निदान नहीं है। आपातकालीन स्थिति में तुरंत 108 पर कॉल करें।',
    'common.privacyNotice': 'नैदानिक गोपनीयता सूचना',
    'common.fieldWorkerGuidelines': 'फील्ड वर्कर दिशानिर्देश',
    'common.copyright': '© राष्ट्रीय ग्रामीण स्वास्थ्य मिशन • राष्ट्रीय स्वास्थ्य पोर्टल',
    'common.activeSession': 'सक्रिय सत्र',
    'common.confidentialAssessment': 'गोपनीय नैदानिक मूल्यांकन',
    'common.companion': 'नलम साथी',
    'common.today': 'आज',
    'common.priority': 'प्राथमिकता',

    // Sidebar Items
    'nav.home': 'होम',
    'nav.symptomChat': 'लक्षण चैट',
    'nav.triageRecord': 'ट्राइएज रिकॉर्ड',
    'nav.staffLogin': 'स्टाफ लॉगिन',
    'nav.staffDashboard': 'पीएचसी ट्राइएज कतार',
    'nav.caseReview': 'केस समीक्षा',
    'nav.phcLocator': 'नजदीकी पीएचसी केंद्र',

    // Header Links
    'header.symptomCheck': 'लक्षण जांच',
    'header.howItWorks': 'यह कैसे काम करता है',
    'header.nearbyPhc': 'नजदीकी पीएचसी केंद्र',

    // Home Hero
    'home.heroPill': 'नलम AI',
    'home.heroTitle1': 'आपका एआई स्वास्थ्य',
    'home.heroTitle2': 'सहायक',
    'home.heroSubtitle': 'अपने लक्षणों का वर्णन करें। आगे क्या करना है इसका त्वरित मार्गदर्शन प्राप्त करें।',
    'home.assessmentTitle': 'तत्काल नैदानिक मूल्यांकन',
    'home.assessmentSubtitle': 'खाते की आवश्यकता नहीं • निजी और सुरक्षित',
    'home.startCheck': 'स्वास्थ्य जांच शुरू करें',
    'home.speakInLanguage': 'अपनी भाषा में बोलें',
    'home.listening': 'आपकी आवाज सुन रहा है...',
    'home.listeningDesc': 'अब हिंदी, तमिल या अंग्रेजी में बोलें',
    'home.continueChat': 'इस पाठ के साथ चैट जारी रखें',
    'home.speechUnsupported': 'इस ब्राउज़र में आवाज पहचान समर्थित नहीं है। कृपया चैट में टाइप करें।',
    'home.speechDenied': 'माइक्रोफ़ोन अनुमति अस्वीकृत। कृपया ब्राउज़र सेटिंग्स में माइक्रोफ़ोन की अनुमति दें।',
    'home.speechError': 'आवाज नहीं पहचानी जा सकी। कृपया स्पष्ट रूप से बोलें या टाइप करें।',
    'home.reviewSpoken': 'बोले गए लक्षणों की समीक्षा करें और संपादित करें:',
    'home.clearText': 'मिटाएं',

    // Home 4-Feature Strip
    'feat.quickAssessment': 'त्वरित मूल्यांकन',
    'feat.quickAssessmentSub': 'मिनटों में मार्गदर्शन प्राप्त करें',
    'feat.ruralCommunity': 'ग्रामीण समुदायों के लिए',
    'feat.ruralCommunitySub': 'स्थानीय आवश्यकताओं के लिए अनुकूलित',
    'feat.safePrivate': 'सुरक्षित और निजी',
    'feat.safePrivateSub': 'आपका डेटा पूरी तरह सुरक्षित है',
    'feat.accessibleCare': 'सुलभ स्वास्थ्य सेवा',
    'feat.accessibleCareSub': 'नजदीकी पीएचसी केंद्रों से जुड़ें',

    // Symptom Chat Screen
    'chat.welcome': 'नमस्ते! मैं नलम हूँ, आपका ग्रामीण स्वास्थ्य सहायक। इस समय आपको या आपके परिवार के सदस्य को क्या लक्षण महसूस हो रहे हैं?',
    'chat.defaultPatientMsg': 'मेरी माँ को 3 दिनों से लगातार सूखी खांसी और हल्का बुखार है। उन्हें कमजोरी भी लग रही है।',
    'chat.botFollowUp': 'मैं समझ गया। क्या उन्हें सीने में भारीपन, सांस लेने में तकलीफ या आराम करते समय कठिनाई हो रही है?',
    'chat.quickOption1': 'सांस लेने में कोई तकलीफ नहीं',
    'chat.quickOption2': 'हल्का सीने में भारीपन है',
    'chat.quickOption3': 'आज बुखार अधिक है',
    'chat.inputPlaceholder': 'अपने लक्षण टाइप करें या बोलने के लिए माइक दबाएं...',
    'chat.send': 'भेजें',
    'chat.listeningState': 'सुन रहा हूँ... अब बोलें',
    'chat.reviewTriageBtn': 'आधिकारिक ट्राइएज रिकॉर्ड और मार्गदर्शन देखें',
    'chat.tapToSpeak': 'बोलने के लिए टैप करें',
    'chat.stopSpeaking': 'सुनना बंद करें',
    'chat.speechHelp': 'आप हिंदी, अंग्रेजी या तमिल में बोल या लिख सकते हैं। सब कुछ पूरी तरह गोपनीय और सुरक्षित है।',
    'chat.consultPhcNotice': 'क्योंकि लक्षण लगातार बने हुए हैं, बुनियादी रक्त जांच और स्वास्थ्य मूल्यांकन के लिए नजदीकी पीएचसी जाएं।',
    'chat.emergencyWarning': 'कृपया ध्यान दें: सांस लेने में कठिनाई या सीने में दर्द तत्काल चिकित्सा की मांग करता है। ट्राइएज रिकॉर्ड #TN-4082-89 तैयार किया गया है।',

    // Triage Record Screen
    'triage.recordTitle': 'आधिकारिक ट्राइएज रिकॉर्ड',
    'triage.evaluatedToday': 'मूल्यांकन किया गया • आज 10:42 AM IST',
    'triage.badgeRecommended': 'चिकित्सकीय परामर्श की सिफारिश की गई',
    'triage.headline': 'अपने प्राथमिक स्वास्थ्य केंद्र (PHC) जाएं',
    'triage.body': 'आपके लक्षणों का 24 घंटे के भीतर स्थानीय प्राथमिक स्वास्थ्य केंद्र के चिकित्सक द्वारा मूल्यांकन किया जाना चाहिए।',
    'triage.code': 'ट्राइएज कोड',
    'triage.priorityLevel': 'प्राथमिकता 2',
    'triage.codeSub': 'समय पर पीएचसी उपचार आवश्यक',
    'triage.observation': 'अवलोकन',
    'triage.observationDesc': 'सूखी खांसी के साथ लगातार बुखार • कोई तीव्र सायनोसिस नहीं',
    'triage.suggestedAction': 'अनुशंसित कार्रवाई',
    'triage.suggestedActionDesc': 'नजदीकी पीएचसी में सीबीसी और बलगम / वायरल जांच',
    'triage.clinicalGuidanceTitle': 'नैदानिक मार्गदर्शन और अगले कदम',
    'triage.step1': 'कठिन शारीरिक परिश्रम से बचें और हवादार कमरे में विश्राम करें।',
    'triage.step2': 'उबला हुआ पानी, ओआरएस या नारियल पानी पीकर हाइड्रेशन बनाए रखें।',
    'triage.step3': 'यदि तेज बुखार (>102°F) या सीने में जकड़न हो, तो तुरंत 108 डायल करें।',
    'triage.findNearbyPhc': 'नजदीकी पीएचसी खोजें और डॉक्टरों की स्थिति देखें',
    'triage.shareRecord': 'रिकॉर्ड साझा करें / प्रिंट करें',
    'triage.toastShared': 'ट्राइएज रिकॉर्ड लिंक कॉपी कर लिया गया!',
    'triage.emergencyHelpline': 'आपातकालीन एम्बुलेंस: 108 • 24/7 स्वास्थ्य हेल्पलाइन: 104',

    // PHC Locator Screen
    'locator.badge': 'राष्ट्रीय ग्रामीण स्वास्थ्य मिशन • पीएचसी निर्देशिका',
    'locator.title': 'नजदीकी प्राथमिक स्वास्थ्य केंद्र (PHC)',
    'locator.subtitle': 'आपके नलम एआई ट्राइएज रिकॉर्ड #TN-4082-89 से समन्वयित सरकारी स्वास्थ्य केंद्र।',
    'locator.backToTriage': '← ट्राइएज रिकॉर्ड पर वापस जाएं',
    'locator.newCheck': 'नई लक्षण जांच',
    'locator.opdOpen': '24/7 आपातकालीन और ओपीडी खुली है',
    'locator.queueEstimate': 'प्राथमिकता कतार प्रतीक्षा',
    'locator.availableBeds': 'अवलोकन बिस्तर उपलब्ध हैं',
    'locator.callPhc': 'केंद्र पर कॉल करें',
    'locator.bookSlot': 'टोकन बुक करें / पीएचसी को सूचित करें',
    'locator.bookedSuccess': 'पीएचसी ड्यूटी नर्स को सूचित कर दिया गया है। कृपया केंद्र पर पहुंचे।',
    'locator.distance': 'किमी दूर',

    // Staff Login Screen
    'login.badge': 'पीएचसी क्लिनिकल नोड 4082 • ऑनलाइन',
    'login.mission': 'ग्रामीण स्वास्थ्य मिशन',
    'login.authorizedTerminal': 'अधिकृत स्टाफ टर्मिनल',
    'login.title': 'नलम एआई स्टाफ स्टेशन',
    'login.subtitle': 'त्वरित नैदानिक प्राथमिकता के साथ चिकित्सा अधिकारियों, नर्सों और फील्ड कार्यकर्ताओं की सहायता।',
    'login.staffIdLabel': 'स्टाफ आईडी / स्वास्थ्य कार्यकर्ता आईडी',
    'login.passwordLabel': 'पासवर्ड / पिन कोड',
    'login.rememberTerminal': 'इस शिफ्ट के लिए टर्मिनल याद रखें',
    'login.signInBtn': 'स्टेशन में प्रवेश करें',
    'login.signingIn': 'पहचान सत्यापित हो रही है...',
    'login.demoHint': 'डेमो एक्सेस: परीक्षण के लिए क्रेडेंशियल पहले से भरे गए हैं',

    // Staff Dashboard Screen
    'dashboard.portal': 'पीएचसी स्टाफ पोर्टल',
    'dashboard.stationNode': 'आलंगुलम प्राथमिक स्वास्थ्य केंद्र (नोड 4082)',
    'dashboard.district': 'तिरुनेलवेली जिला क्लस्टर',
    'dashboard.liveStream': 'लाइव ट्राइएज स्ट्रीम सक्रिय',
    'dashboard.dutyDoctor': 'ड्यूटी डॉक्टर: डॉ. प्रिया आर.',
    'dashboard.tabQueue': 'ट्राइएज कतार',
    'dashboard.tabActive': 'सक्रिय मामले',
    'dashboard.tabReferrals': 'आपातकालीन रेफरल और 108',
    'dashboard.tabAnalytics': 'महामारी निगरानी',
    'dashboard.filterAll': 'सभी मामले',
    'dashboard.filterEmergency': 'आपातकालीन (लाल)',
    'dashboard.filterUrgent': 'गंभीर (नारंगी)',
    'dashboard.filterRoutine': 'सामान्य (हरा)',
    'dashboard.totalCases': 'कुल मामले',
    'dashboard.todayIntake': 'आज के पंजीकरण',
    'dashboard.emergency': 'आपातकालीन',
    'dashboard.urgent': 'गंभीर',
    'dashboard.routine': 'सामान्य',
    'dashboard.priority1': 'प्राथमिकता 1',
    'dashboard.priority2': 'प्राथमिकता 2',
    'dashboard.standard': 'मानक',
    'dashboard.immediateDoctorReview': 'तत्काल डॉक्टर समीक्षा',
    'dashboard.within2Hours': '2 घंटे के भीतर',
    'dashboard.standardQueue': 'सामान्य कतार',
    'dashboard.priorityCases': 'प्राथमिकता वाले मामले',
    'dashboard.updatedLive': 'लाइव अपडेट',
    'dashboard.allCasesFilter': 'सभी मामले',
    'dashboard.tableCaseId': 'केस आईडी',
    'dashboard.tableDemographic': 'रोगी विवरण',
    'dashboard.tableChief': 'मुख्य लक्षण और शिकायत',
    'dashboard.tableChiefSymptom': 'मुख्य लक्षण',
    'dashboard.tableSeverity': 'गंभीरता स्तर',
    'dashboard.tableTriageLevel': 'ट्राइएज स्तर',
    'dashboard.tableIntakeTime': 'पंजीकरण समय',
    'dashboard.tableTime': 'समय',
    'dashboard.tableAction': 'कार्रवाई',
    'dashboard.medicalAttention': 'चिकित्सीय ध्यान',
    'dashboard.reviewCase': 'समीक्षा करें',
    'dashboard.viewCase': 'केस देखें',
    'dashboard.reviewed': 'समीक्षित',
    'dashboard.dispatchAmbulance': '108 एम्बुलेंस भेजी गई',
    'dashboard.footerVerification': 'आईसीएमआर प्राथमिक स्वास्थ्य प्रोटोकॉल के अनुसार एआई ट्राइएज सत्यापित',
    'dashboard.showingCases': 'सक्रिय मामले प्रदर्शित हैं',

    // Case Review Screen
    'case.back': '← ट्राइएज कतार पर वापस जाएं',
    'case.backToPriority': 'प्राथमिकता मामलों पर वापस जाएं',
    'case.caseReviewTitle': 'विस्तृत नैदानिक केस समीक्षा',
    'case.vitals': 'फील्ड वाइटल्स रिकॉर्ड',
    'case.symptomsDetails': 'दर्ज किए गए लक्षण और प्रगति',
    'case.ashaReport': 'आशा कार्यकर्ता फील्ड रिपोर्ट',
    'case.voiceIntake': 'रोगी की आवाज रिकॉर्डिंग विवरण',
    'case.playAudio': 'रोगी की वॉयस नोट सुनें',
    'case.pauseAudio': 'वॉयस नोट रोकें',
    'case.actionChecklist': 'क्लिनिकल निर्देश चेकलिस्ट',
    'case.markComplete': 'स्वीकृत करें और ड्यूटी डॉक्टर को भेजें',
    'case.trigger108': '108 एएलएस एम्बुलेंस भेजें',
    'case.dispatch108': '108 एम्बुलेंस भेजें',
    'case.ambulanceDispatched': '108 एम्बुलेंस भेजी गई',
    'case.addNote': 'डॉक्टर नोट जोड़ें',
    'case.addClinicalNote': 'क्लिनिकल नोट जोड़ें',
    'case.saveNote': 'नोट सहेजें',
    'case.cancel': 'रद्द करें',
    'case.notePlaceholder': 'नैदानिक अवलोकन या डॉक्टर निर्देश दर्ज करें...',
    'case.confirmAmbulanceTitle': '108 एएलएस एम्बुलेंस भेजने की पुष्टि करें',
    'case.confirmAmbulanceDesc': 'यह निकटतम 108 इकाई को रोगी के स्थान और महत्वपूर्ण संकेतों के साथ आपातकालीन अनुरोध भेजेगा।',
    'case.confirmDispatchBtn': 'आपातकालीन प्रेषण की पुष्टि करें',
    'case.reviewedRouted': 'स्वीकृत और डॉक्टर को भेजा गया',
    'case.noteSaved': 'क्लिनिकल नोट सहेजा गया और रिकॉर्ड से संलग्न किया गया।',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export const LanguageProvider: React.FC<{
  language: LanguageCode;
  onLanguageChange: (lang: LanguageCode) => void;
  children: React.ReactNode;
}> = ({ language, onLanguageChange, children }) => {
  const t = (key: string, fallback?: string): string => {
    const langDict = translations[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    const enDict = translations['en'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: onLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  return useContext(LanguageContext);
};
